mltrons/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^upload/', include('uploadfile.urls')),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
	urlpatterns += static(settings.FILE_URL, document_root=settings.FILE_URL)

music/urls.py
from django.conf.urls import url
from . import views

app_name = "music"

urlpatterns = [
  url(r'^$', views.index, name='index'),

  # /music/234
  url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

  # /music/234/favorite/
  url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

uploadfile/urls.py
from django.conf.urls import url
from . import views

app_name = "uploadfile"
urlpatterns = [
  url(r'^$', views.FileFormCreate.as_view(), name='index'),

]

dashboard/models.py
from django.db import models

# Create your models here.

music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)

	def __str__(self):
		return self.album_title + ' - ' + self.artist 

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=50)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title 

uploadfile/models.py
from django.db import models
from django.core.urlresolvers import  reverse

# Create your models here.
class File(models.Model):
	name = models.CharField(max_length=250)
	file_title = models.CharField(max_length=500)
	company = models.CharField(max_length=100)
	file_url = models.FileField()
	file_type = models.CharField(max_length=100)
	# file_actual =  models.FileField()

	def get_absolute_url(self):
		return reverse('uploadfile:index')
		
	def __str__(self):
		return self.name + ' - ' + self.company 

dashboard/views.py
from django.shortcuts import render

# Create your views here.

music/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from django.template import loader
from .models import Album

# Create your views here.
def index(request):
	all_albums = Album.objects.all()
	# template = loader.get_template('music/index.html')
	context = {
		'all_albums': all_albums,
	}
	# return HttpResponse(template.render(context, request))
	return render(request, 'music/index.html', context)
 

def detail(request, album_id):
	# try:
	# 	album = Album.objects.get(pk=album_id)
	# except Album.DoesNotExist:
	# 	raise Http404("Album does not exist")
	album = get_object_or_404(Album, pk=album_id)
	return render(request, 'music/detail.html', {'album': album})

def favorite(request, album_id):
	album = get_object_or_404(Album, pk=album_id)
	try:
		selected_song = album.song_set.get(pk=request.POST['song'])
	except (KeyError, doesNotExist):
		return render(request, 'music/detail.html', {
			'album': album,
			'error_message': "You did not return a valid song",
		})
	else :
		selected_song.is_favorite = True
		selected_song.save()
		return render(request, 'music/detail.html', {'album': album})

	

uploadfile/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from django.template import loader
from .models import File
from django.views.generic.edit import CreateView
from django.views import generic

# Create your views here.
def index(request):
	all_files = File.objects.all()
	# template = loader.get_template('music/index.html')
	context = {
		'all_files': all_files,
	}
	# return HttpResponse(template.render(context, request))
	return render(request, 'uploadfile/index.html', context)

class FileFormCreate(CreateView):
	model = File
	fields = ['name','company','file_type','file_url', 'file_title']

music/templates/music/detail.html
<img src="{{album.album_logo}}">

<h1> {{album.album_title}} </h1>
<h2> {{album.artist}} </h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id%}" method="post">
	{% csrf_token %}
	{% for song in album.song_set.all %}
		<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
		<label for="song{{ forloop.counter }}">
			{{ song.song_title }}
			{% if song.is_favorite %}
				<img src="http://i.imgur.com/b9b13Rd.png" />
			{% endif %}
		</label><br>
	{% endfor %}
	<input type="submit" value="favorite">
</form>

music/templates/music/index.html
<ul>
	{% for album in all_albums %}
	<li><a href="{% url 'music:detail' album.id%}">{{album.album_title}}</a></li>
	{% endfor %}
</ul>

uploadfile/templates/uploadfile/base.html
<!doctype html>
<html lang='en'>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>MLTrons</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'uploadfile/style.css' %}">
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
		<!-- Header -->
		<div class="container-fluid">
		
			<!--Logo -->
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'uploadfile:index' %}">
					MLTrons
				</a>
			</div>

			<!-- Items -->
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="active">
						<a href="{% url 'uploadfile:index' %}">
							<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp
							Home
						</a>
					</li>
					<li class="">
						<a href="{% url 'uploadfile:index' %}">
							<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp
							DataStore
						</a>
					</li>
					<li class="">
						<a href="{% url 'uploadfile:index' %}">
							<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp
							Models
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	{% block body %}

	{% endblock%}


</body>

uploadfile/templates/uploadfile/file_form.html
{% extends 'uploadfile/base.html' %}

{% block body %}
<div class="container-fluid">
	<div class="col-sm-12 col-md-7">
		<div class="panel panel-default">
			<div class="panel-body">
				
				<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{% include 'uploadfile/form-template.html' %}
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock%}

uploadfile/templates/uploadfile/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
			<label class="control-label col-sm-2"> {{ field.label_tag }}</label>
			<div class="col-sm-10"> {{field}}</div>
		</div>
	</div>
{% endfor %}

uploadfile/templates/uploadfile/index.html
{% extends 'uploadfile/base.html' %}


{% block body %}
<div class="container-fluid">
	<div class="col-sm-12 col-md-7">
		<div class="panel panel-default">
			<div class="panel-body">
				
				<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{% include 'uploadfile/form-template' %}
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock%}